# Generated by Django 3.1.7 on 2021-03-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="preparation_time",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
